# Path to your oh-my-zsh installation.
export ZSH=/Users/rmlynch/.oh-my-zsh

ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"

plugins=(git autojump docker)

export PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

source $ZSH/oh-my-zsh.sh

# User Customization

command_exists () {
  type "$1" &> /dev/null ;
}

# RVM / Ruby
if [ -d "$HOME/.rvm" ]; then
  export PATH="$PATH:$HOME/.rvm/bin"
fi

# Hub
if command_exists hub; then
  eval "$(hub alias -s)"
fi

# Pick which vim to use
if command_exists neovim; then
  alias vim=neovim
fi
